blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging
      proxy:
        resources:
          requests:
            memory: 4Gi
            cpu: 500m
    poolSize: 100
    resources:
      requests:
        memory: 12Gi
        cpu: 5
  api:
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging-replica
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
  web:
    host: rc1staging-blockscout.celo-testnet.org
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 250M
        cpu: 500m
    stats:
      enabled: true
      reportUrl: '{"overview": "https://datastudio.google.com/embed/reporting/1a4324da-ed18-40ff-954b-5e621fa6cb3a/page/hDehC?hl=en", "addresses":"https://datastudio.google.com/embed/reporting/9524e606-ff9d-498b-9cee-1e139a25d458/page/hDehC?hl=en", "cStables":"https://datastudio.google.com/embed/reporting/0dd3299c-1133-4f32-9ec8-9a409924b69a/page/hDehC?hl=en", "transactions":"https://datastudio.google.com/embed/reporting/c5a8beb4-a3e8-478e-bdc1-c7acd39abcd2/page/hDehC?hl=en", "reserve": "https://datastudio.google.com/embed/reporting/082743c9-5f65-46b5-b4ef-3c1c38729042/page/hDehC?hl=en"}'
  metadataCrawler:
    enabled: true
  archiveNodes:
    jsonrpcHttpUrl: http://rc1staging-archivenodes-rpc:8545
    jsonrpcWsUrl: ws://rc1staging-archivenodes-rpc:8545
  metrics:
    enabled: false
  secrets:
    segmentKey: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-segmentKey
    dbUser: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-dbUser
    dbPassword: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-dbPassword
    dbUrl: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-dbUrl
    grafanaCloud: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-grafanaCloud
    recaptcha:
      projectId: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-recaptchaProjectId
      siteKey: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-recaptchaSiteKey
      apiKey: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-recaptchaApiKey
  chain:
    subnetwork: Celo
    networkID: 42220
